---
apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  ports:
  - name: report-service-http
    nodePort: 31787
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moop
    service: report-service
  type: NodePort
